[package]
name = "chain-of-responsibility"
version = "0.1.0"
authors = ["yuer1727 <172742451@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
